### ISSUE TITLE
animated "ank" output causes crash when using Ansible

### ISSUE THREAD

**Issue by sboett-dev** [eclipse-ankaios/ankaios#281]
When running `ank apply` with Ansible, the workload is applied (workload starts as it is wanted) but it fails afterwards with error code 101.

## Current Behavior
```
- name: start-workload
  ansible.builtin.command: "/usr/local/bin/ank apply {{ ansible_env.HOME }}/test/workload-test.yml"
```

results in:
```
command: /usr/local/bin/ank apply /home/ewaol/test/workload-test.yml
return code: 101
stderr:
  thread 'main' panicked at ank/src/log.rs:79:22:
  chunk size must be non-zero\nstack backtrace:
     0: rust_begin_unwind
     at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
     1: core::panicking::panic_fmt
     at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
     2: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
     3: <core::iter::adapters::flatten::FlatMap<I,U,F> as core::iter::traits::iterator::Iterator>::next
     4: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
     5: ank::log::output_update_fn
     6: ank::cli_commands::wait_list::WaitList<T>::update
     7: ank::cli_commands::CliCommands::update_state_and_wait_for_complete::{{closure}}
     8: ank::main::{{closure}}\n   9: tokio::runtime::park::CachedParkThread::block_on
     10: ank::main
     note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stdout: 
```
The workload does in fact start, but the command crashes afterwards.

## Expected Behavior
error code: 0 and no crash

## Steps to Reproduce

1. create an ansible project
2. write a task like so with any workload.yml:
```
- name: start-workload
  ansible.builtin.command: "/usr/local/bin/ank apply workload.yml"
```
4. execute the playbook
5. see it fail

## Logs
see above

## Additional Information
```
chunk size must be non-zero
```
The `log.rs` file probably fails to determine the terminal size for the animated output. This results in a chunk size of zero.

## Final result

**To be filled by the one closing the issue.**

**Comment by krucod3** [comment]
@sboett-dev, thanks for logging the issue! 
I somehow cannot reproduce it. I tried with ansible [core 2.17.0].
Which version did you used?

**Comment by krucod3** [comment]
If you are still experiencing the problem, you could try using the `--quite` option as a workaround:
`ank --quiet apply workload.yml` 

Unfortunately I cannot verify if this works as I cannot reproduce the issue.
Please provide the Context (Environment) that you are using including the OS, the ansible version and the Ankaios version. This is required part of the issue description for a bug ticket.

**Comment by sboett-dev** [comment]
@krucod3 Sorry I forgot to add the versions:
I am using Ubuntu (locall dev container) and try to deploy to EWAOL.
```
ansible [core 2.16.2]
  config file = None
  configured module search path = ['/home/vscode/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/py-utils/venvs/ansible-core/lib/python3.10/site-packages/ansible
  ansible collection location = /home/vscode/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/py-utils/bin/ansible
  python version = 3.10.13 (main, Jan  5 2024, 16:55:56) [GCC 10.2.1 20210110] (/usr/local/py-utils/venvs/ansible-core/bin/python)
  jinja version = 3.1.2
  libyaml = True
```
`ank --quiet apply` works (no output at all and return code=0)

**Comment by krucod3** [comment]
@krucod3, it's probably related to the target platform. Do you know which shell is used in EWAOL?

**Comment by krucod3** [comment]
Fixed.
